/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-23 06:08:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import order.model.vo.PageInfo;
import order.model.vo.Order;
import java.util.List;
import java.util.Date;
import java.text.SimpleDateFormat;
import member.model.vo.Employee;
import member.model.service.EmpService;
import member.model.vo.Employee;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/order/../common/navbar.jsp", Long.valueOf(1595144080000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/footer.jsp", Long.valueOf(1594349126000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/footerScript.jsp", Long.valueOf(1594450848000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/header.jsp", Long.valueOf(1595393108085L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/meta.jsp", Long.valueOf(1593265000000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/sidebar.jsp", Long.valueOf(1595039526000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("order.model.vo.Order");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("order.model.vo.PageInfo");
    _jspx_imports_classes.add("member.model.vo.Employee");
    _jspx_imports_classes.add("member.model.service.EmpService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	PageInfo pi = (PageInfo) request.getAttribute("pi");
	List<Order> orderList = (List<Order>) request.getAttribute("orderList");
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일");
	String[] search = request.getParameterValues("search");
	String msg = (String)session.getAttribute("msg");


	int currentPage = pi.getCurrentPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	int maxPage = pi.getMaxPage();
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
      out.write("\r\n");
      out.write("<title>발주</title>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/css/style.css\">\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/favicon.png\" />\r\n");
      out.write("<!-- font 적용-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".popup_panel { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 100;}\r\n");
      out.write(".popup_panel div.popup_bg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; background:#000; opacity:.5; filter:alpha(opacity=50); }\r\n");
      out.write(".popup_panel div.popup_contents { position: absolute; top: 30%; left: 50%; width:600px; hight:800px; border:2px solid #b66dff; background-color:#fff; }\r\n");
      out.write(".popup_contents2 {display:inline; float: right; margin: 30px; margin-top: 63px; margin-right: 38px;}\r\n");
      out.write(".stock-tr {\r\n");
      out.write("\t/* font-family: 고딕; */\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar message = \"");
      out.print(msg);
      out.write("\";\r\n");
      out.write("\t\t// var message = \"회원가입 성공!!\"; // \"null\"\r\n");
      out.write("\t\tif(message != \"null\"){\r\n");
      out.write("\t\t\talert(message);\r\n");
      out.write("\t\t\t");
 session.removeAttribute("msg"); 
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");


      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-scroller\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
 
	Employee empLoggedIn = (Employee) session.getAttribute("empLoggedIn");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_navbar.html -->\r\n");
      out.write("<nav class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("  <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("    <a class=\"navbar-brand brand-logo\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo.png\" alt=\"logo\" /></a>\r\n");
      out.write("    <a class=\"navbar-brand brand-logo-mini\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo-mini.svg\" alt=\"logo\" /></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler align-self-center\" type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"search-field d-none d-md-block\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("      <li class=\"nav-item nav-profile dropdown\" style=\"margin-top: 2%;\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <div class=\"nav-profile-text\" >\r\n");
      out.write("          ");
if(empLoggedIn != null){
      out.write("\r\n");
      out.write("          <p class=\"mb-1 text-black\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/infoView?eCode=");
      out.print(empLoggedIn.geteCode());
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(empLoggedIn.geteDept());
      out.write(" <strong>");
      out.print(empLoggedIn.geteName() );
      out.write("</strong></p>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-lg-block full-screen-link\">\r\n");
      out.write("        <a class=\"nav-link\">\r\n");
      out.write("          <i class=\"mdi mdi-fullscreen\" id=\"fullscreen-button\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\t  <li class=\"nav-item\">\r\n");
      out.write("\t    <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath());
      out.write("/board/boardList\">\r\n");
      out.write("\t  \t<i class=\"mdi mdi-bulletin-board\"></i>\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t  </li>\r\n");
      out.write("      <li class=\"nav-item nav-logout d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("          <i class=\"mdi mdi-power\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item nav-settings d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("          <i class=\"mdi mdi-format-line-spacing\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t\t<!-- partial -->\r\n");
      out.write("\t\t<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Employee user = (Employee) session.getAttribute("empLoggedIn");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("  <ul class=\"nav\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("\">\r\n");
      out.write("        <span class=\"menu-title kor\">메 인</span>\r\n");
      out.write("        <i class=\"mdi mdi-home menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#product\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">상품관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-basket menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"product\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/warehousing?currentPage=1\">입고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/beReleased\">출고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/stk\">재고</a></li> \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#order\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">거래관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-barcode-scan menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"order\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/ordr?currentPage=1\">발주</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/transfer\">이송</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("       <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/sales\">\r\n");
      out.write("        <span class=\"menu-title kor\">통 계</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-chart-line menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/approval?currentPage=1\">\r\n");
      out.write("        <span class=\"menu-title kor\">결재진행</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-script menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t\t\t<!-- partial -->\r\n");
      out.write("\t\t\t<div class=\"main-panel\">\r\n");
      out.write("\t\t\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mdi mdi-close\" id=\"bannerClose\" style=\"display: none;\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\"page-header\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: inline-block; width: 50%; text-align: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"page-title kor\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"display: inline-block; margin-right: 25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"page-title-icon bg-gradient-primary text-white mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-barcode-scan\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span> 발 주\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"display: inline-block; width: 50%; text-align: right; padding-right: 40px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-inverse-success btn-rounded btn-icon\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" data-placement=\"top\" title=\"발주 엑셀폼 다운로드\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<a download=\"order.xlsx\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/order.xlsx\"><i class=\"mdi mdi-file-excel\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn-group\" style=\"float: right !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-link dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\">+ New Order</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item kor trigger\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-weight: 300; font-size: 14px;\" href=\"\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderForm?eCode=");
      out.print(empLoggedIn.geteCode());
      out.write("',\r\n");
      out.write("\t\t\t\t            \t\t\t'_blank', 'top=1,left=500,width=1000,height=700')\">직접 입력</a> <a class=\"dropdown-item kor\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-weight: 300; font-size: 14px;\" data-toggle=\"modal\" data-target=\"#myModal\">엑셀 업로드</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br claer=\"both\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"order-main\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form class=\"form-sample\" id=\"searchForm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/searchCompleteOrder\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 col-form-label stock-tr\">발주코드</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"search\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 col-form-label stock-tr\">상품코드</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"search\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 col-form-label stock-tr\">출고센터</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tform=\"searchForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"GG\">광주센터</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"TK\">대구센터</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 col-form-label stock-tr\">주문매장</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tform=\"searchForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S001\">코엑스 별마당</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"s002\">압구정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"s003\">강남오거리</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"s004\">강남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"s005\">한티역</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"s006\">도산가로수길</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S007\">수원시청</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S008\">수원성균관대</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S009\">범계역</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S010\">킨텍스이마트</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option disabled>-----------</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S11\">대구수목원</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S12\">대구동천</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S13\">경북대</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S14\">부산대연역</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S15\">수영강변</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 col-form-label stock-tr\">기간</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" name=\"search\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 col-form-label stock-tr\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center\"> - </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" name=\"search\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-inverse-info btn-fw\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"float: left\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/ordr?currentPage=1'\">전체보기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"currentPage\" value=\"1\" form=\"searchForm\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-inverse-primary btn-fw\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"float: right\">Search</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-12 grid-margin\" style=\"margin-top: 26px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <h4 class=\"card-title\">발주 리스트</h4> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: bold;\">발주번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: bold;\">출고센터</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: bold;\">상품코드</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: bold;\">주문수량</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: bold;\">주문매장</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: bold;\">주문일자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												if (orderList == null || orderList.isEmpty()) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th colspan=\"6\">조회된 행이 없습니다.</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												} else {
													for (Order o : orderList) {
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" style='color:#b66dff'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"window.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderDetailForm?oCode=");
      out.print(o.getoCode());
      out.write("',\r\n");
      out.write("\t\t\t\t            \t\t\t'_blank', 'top=1,left=500,width=1000,height=700')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(o.getoCode());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													if (o.getcCode().equals("GG")) {
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><label class=\"badge badge-gradient-danger\">경기광주</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													} else {
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><label class=\"badge badge-gradient-info\">대구</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"javascript:void(0)\" class=\"btn_popup_open\" style='color:#b66dff'> ");
      out.print(o.getpCode());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(o.getoAmount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(o.getsCode());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(sdf.format(o.getoDate()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

													}
												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--  페이징 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (currentPage != 1) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/ordr?currentPage=1\" style=\"color:#b66dff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class='mdi mdi-chevron-double-left' style='color:#b66dff'></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/ordr?currentPage=");
      out.print(currentPage - 1);
      out.write("\" style=\"color:#b66dff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-chevron-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
										for (int p = startPage; p <= endPage; p++) {
										    
											if (currentPage != p) {
											    
												if(search == null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/ordr?currentPage=");
      out.print(p);
      out.write("' style='color:#b66dff'> ");
      out.print( p );
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

												} 
												else
												{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/searchCompleteOrder?currentPage=");
      out.print(p);
      out.write("&search=");
      out.print(search[0]);
      out.write("&search=");
      out.print(search[1]);
      out.write("&search=");
      out.print(search[2]);
      out.write("&search=");
      out.print(search[3]);
      out.write("&search=");
      out.print(search[4]);
      out.write("&search=");
      out.print(search[5]);
      out.write("' style='color:#b66dff'> ");
      out.print( p );
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

												}
											} 
											else 
											{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class='cPage' style='color:#b66dff; font-weight: bold;'>");
      out.print( p );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

											}
										}
										
										if(maxPage != 0) 
										{
											if (currentPage != maxPage) 
											{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/ordr?currentPage=");
      out.print(currentPage + 1);
      out.write("\" style='color:#b66dff'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-chevron-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/ordr?currentPage=");
      out.print(maxPage);
      out.write("\" style='color:#b66dff'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-chevron-double-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

											}
										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- content-wrapper ends -->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_footer.html -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("    <span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright © 2017 <a href=\"#\" target=\"_blank\">STOCKer</a>. All rights reserved.</span>\r\n");
      out.write("    <i class=\"mdi mdi-heart text-danger\" id=\"topBtn\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- partial -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- main-panel ends -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- page-body-wrapper ends -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 레이어 팝업 시작 -->\r\n");
      out.write("\t<div class=\"popup_panel\">\r\n");
      out.write("\t\t<div class=\"popup_bg\"></div>\r\n");
      out.write("\t\t\t<div class=\"popup_contents\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t<!-- images 폴더에 p_code와 같은 이름의 jpg파일 -->\r\n");
      out.write("\t\t\t\t<img id=\"p_image\" src=\"\" alt=\"\" />\r\n");
      out.write("\t\t\t<div class=\"popup_contents2\">\r\n");
      out.write("\t\t\t\t<!-- db product테이블 p_theme 컬럼 --> \r\n");
      out.write("\t\t\t\t<span id=\"p_theme\">p_theme</span>\r\n");
      out.write("\t\t\t\t<!-- db product테이블 p_category 컬럼 -->\r\n");
      out.write("\t\t\t\t<span id=\"p_category\">p_category</span>\r\n");
      out.write("\t\t\t\t<!-- db product테이블 p_name 컬럼 -->\r\n");
      out.write("\t\t\t\t<span id=\"p_name\">p_name</span>\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t<span id=\"p_price\" style=\"float:right\">p_price</span>\r\n");
      out.write("\t\t\t\t<div id=\"qrDiv\" style=\"float: right; margin-top: 40px\">\r\n");
      out.write("\t\t\t\t\t<img id=\"p_qr_image\" src=\"\" alt=\"\" style=\"width:130px; margin-right: -60px;\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 파일 업로드 모달 -->\r\n");
      out.write("\t<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("\t  <div class=\"modal-dialog\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Modal Header -->\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h4 class=\"modal-title\">발주서를 업로드 하세요.</h4>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Modal body -->\r\n");
      out.write("\t      <div class=\"modal-body\">\r\n");
      out.write("\t     \t <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/upload?ecode=");
      out.print( empLoggedIn.geteCode() );
      out.write("\" name=\"upload\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" name=\"filename\" size=\"20\" align=\"absmiddle\" />    </td>\r\n");
      out.write("\t\t\t\t<td><button type=\"button\" class=\"btn btn-inverse-danger btn-fw\" onclick=\"checkForm();\" style=\"cursor:hand\"> 등록 </button></td>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- container-scroller -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<!-- End plugin js for this page -->\r\n");
      out.write("<!-- inject:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/misc.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Custom js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/todolist.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  var topEle = $('#topBtn');\r\n");
      out.write("  var delay = 1000;\r\n");
      out.write("  \r\n");
      out.write("  topEle.on('click', function() {\r\n");
      out.write("    $('html, body').stop().animate({scrollTop: 0}, delay);\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("<!-- End custom js for this page -->");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction checkForm() {  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (upload.filename.value == \"\") \r\n");
      out.write("\t\t{  \r\n");
      out.write("\t\t\talert(\"파일을 업로드해주세요.\");  \r\n");
      out.write("\t\t\treturn false;  \r\n");
      out.write("\t\t}  \r\n");
      out.write("\t\telse if(!checkFileType(upload.filename.value)) \r\n");
      out.write("\t\t{  \r\n");
      out.write("\t\t\talert(\"엑셀파일만 업로드 해주세요.\");  \r\n");
      out.write("\t\t\treturn false;  \r\n");
      out.write("\t\t}  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.upload.submit();\r\n");
      out.write("\t}  \r\n");
      out.write("\t\r\n");
      out.write("\tfunction checkFileType(filePath)\r\n");
      out.write("\t{ \r\n");
      out.write("\t\t\tvar fileLen = filePath.length;  \r\n");
      out.write("\t\t\tvar fileFormat = filePath.substring(fileLen - 5);  \r\n");
      out.write("\t\t\tfileFormatfileFormat = fileFormat.toLowerCase();  \r\n");
      out.write("\t\r\n");
      out.write("\t\t\tif (fileFormat == \".xlsx\")\r\n");
      out.write("\t\t\t   return true;   \r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\treturn false;    \r\n");
      out.write("\t}  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(function () {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 레이어팝업 \r\n");
      out.write("\t    var $panel = $(\".popup_panel\");\r\n");
      out.write("\t    var $panelContents = $panel.find(\".popup_contents\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    //상품상세팝업 클릭했을때\r\n");
      out.write("\t    $(\".btn_popup_open\").on(\"click\", function(e) {\r\n");
      out.write("\t    \t//상품코드 준비\r\n");
      out.write("\t    \tvar pCode = $(this).text();\r\n");
      out.write("\t\t\tvar params = {pCode : pCode}; //서버로 보낼 파라미터\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/productDetail', $.param(params), function(responseJson){\r\n");
      out.write("\t\t\t\t//p_theme, p_category, p_name, p_price, p_qrImage\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar obj = $.parseJSON(JSON.stringify(responseJson));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#p_image\").attr(\"src\", obj.pImage); //파일서블릿 경로(상품이미지 서버위치 가져옴)\r\n");
      out.write("\t\t\t\t$(\"#p_theme\").text(\"[\" + obj.pTheme + \"]\");\r\n");
      out.write("\t\t\t\t$(\"#p_category\").html(\"[\" + obj.pCategory + \"]\" + \"<br>\");\r\n");
      out.write("\t\t\t\t$(\"#p_name\").text(obj.pName);\r\n");
      out.write("\t\t\t\t$(\"#p_price\").text((obj.pPrice).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\")); //가격 콤마찍기 \r\n");
      out.write("\t\t\t\t$(\"#p_qr_image\").attr(\"src\", obj.pQrImage); //파일서블릿 경로(상품QR이미지 서버위치 가져옴)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t        // 팝업 가운데 설정(가로)\r\n");
      out.write("\t        if ($panelContents.outerWidth() < $(document).width()) {\r\n");
      out.write("\t            $panelContents.css(\"margin-left\", \"-\" + $panelContents.outerWidth() / 2 + \"px\");\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t            $panelContents.css(\"left\", \"0px\");\r\n");
      out.write("\t        }\r\n");
      out.write("\r\n");
      out.write("\t        // 팝업 가운데 설정(세로)\r\n");
      out.write("\t        if ($panelContents.outerHeight() < $(document).height()) {\r\n");
      out.write("\t            $panelContents.css(\"margin-top\", \"-\" + $panelContents.outerHeight() / 2 + \"px\");\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t            $panelContents.css(\"top\", \"0px\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t        // 레이어 팝업 열기\r\n");
      out.write("\t        $panel.fadeIn();\r\n");
      out.write("\t        \r\n");
      out.write("\t    });\r\n");
      out.write("\t    // 팝업 닫기 이벤트 정의\r\n");
      out.write("\t    $(\"#btn_popup_close\").on(\"click\", popupClose);\r\n");
      out.write("\r\n");
      out.write("\t    // 팝업 배경 클릭 이벤트 정의\r\n");
      out.write("\t    $panel.find(\".popup_bg\").on(\"click\", popupClose);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction popupClose(e) {\r\n");
      out.write("\t\t    $panel.fadeOut();\r\n");
      out.write("\t\t    // 이벤트 기본 동작 중단\r\n");
      out.write("\t\t    e.preventDefault();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
