/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-20 03:15:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Employee;
import sales.model.vo.Shop;
import product.model.vo.Product;
import order.model.vo.Order;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class orderForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/order/../common/footerScript.jsp", Long.valueOf(1594450848000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/header.jsp", Long.valueOf(1593330696000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/meta.jsp", Long.valueOf(1593265000000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("order.model.vo.Order");
    _jspx_imports_classes.add("product.model.vo.Product");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("member.model.vo.Employee");
    _jspx_imports_classes.add("sales.model.vo.Shop");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();
	Order order = (Order) request.getAttribute("order");
	Product product = (Product) request.getAttribute("product");
	Shop shop = (Shop) request.getAttribute("shop");
	String cName = order != null ? ((order.getcCode()).equals("GG") ? "경기센터" : "대구센터") : "";
	Employee writer = (Employee) request.getAttribute("emp"); 
	
	// System.out.println("order = " + order);
	
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일");
	Date now = new Date();
	String today = sdf.format(now);
	String msg = (String) session.getAttribute("msg");
	Employee empLoggedIn = (Employee) session.getAttribute("empLoggedIn");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("\t ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
      out.write("\r\n");
      out.write("\t <title>발주서 상세보기</title>\r\n");
      out.write("\t ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/css/style.css\">\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/favicon.png\" />\r\n");
      out.write("<!-- font 적용-->\r\n");
      out.write("<!-- 한글 폰트 적용 : 해당 태그 클래스에 'kor' 기입 -->\r\n");
      out.write("<!-- font-family: 'Noto Sans KR', sans-serif; -->\r\n");
      out.write("<!-- font-weight은 100, 300, 400(default), 500, 700, 900 가능합니다. -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.kor {\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t\tcolor: #343A40;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("input {\r\n");
      out.write(" background-color: white !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("  ");

  	if(msg != null && !msg.equals(""))
  	{
  
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\talert(\"");
      out.print( msg );
      out.write("\"); \r\n");
      out.write("\t\t\tself.close();\r\n");
      out.write("\t\t</script>\r\n");
      out.write("  ");

  		session.removeAttribute("msg");
  	}
  
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!--     <div class=\"container-scroller\"> -->\r\n");
      out.write("      <!-- partial -->\r\n");
      out.write("      <div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("        <!-- partial -->\r\n");
      out.write("        <div class=\"main-panel\" style=\"width: 100%;\">\r\n");
      out.write("          <div class=\"content-wrapper\">\r\n");
      out.write("              <i class=\"mdi mdi-close\" id=\"bannerClose\" style=\"display: none;\"></i>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <div style=\"padding-right: 20px;\">\r\n");
      out.write("\t          <div style=\"float:left; display: inline-block; margin-top: 48px; margin-left: 26px;\"><h1 class=\"display-1 kor\"> 발주서 </h1></div>\r\n");
      out.write("\t\t\t  <div class=\"card\" style=\"display: inline-block; margin-top: 26px; width:148px; float:right\" >\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<table style=\"border-spacing:10px; text-align:center\">\r\n");
      out.write("\t\t\t\t\t\t<tr><th class=\"kor\"><strong>재고 담당</strong></th></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td><input type=\"checkbox\" ");
      out.print( order != null ? (order.getoStatus().equals('C') ? "checked" : "") : "" );
      out.write(" disabled></td></tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <form class=\"forms-sample\" id=\"orderForm\" action=\"");
      out.print( contextPath );
      out.write("/order/submitOrder\" method=\"post\">\r\n");
      out.write("\t\t  \r\n");
      out.write("          <div class=\"col-lg-12 grid-margin stretch-card\" style=\"margin-top: 30%\">\r\n");
      out.write("\t\t\t  <div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t  <table class=\"table\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"kor\"><strong>품의 제목</strong></th>\r\n");
      out.write("\t\t\t\t\t\t<th><input type=\"text\" name=\"title\" id=\"title\" class=\"form-control kor\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   placeholder=\"제목을 입력하세요.\" value=\"");
      out.print( order != null ? order.getoTitle() : "" );
      out.write("\" required\r\n");
      out.write("\t\t\t\t\t\t\t\t   ");
      out.print( order != null ? "disabled" : "" );
      out.write("/></th>\r\n");
      out.write("\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t<th><strong>발주 내용</strong></th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\t\r\n");
      out.write("\t\t\t\t\t\t\t");

								if(order == null) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"addProductInput\" placeholder=\"상품코드로 검색\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <button class=\"btn btn-sm btn-gradient-primary\" id=\"addProductBtn\" type=\"button\">Search</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} 
							
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table product\" id=\"addProductTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr style=\"border-color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if(order == null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <th style=\"width: 11%;\"> <input type=\"checkbox\" id=\"selectAll\" onclick=\"selectAllCheckBox();\"/> </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <th style=\"font-weight: bold;\"> 상품코드 </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <th style=\"width: 21%; font-weight: bold;\"> 상품명 </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <th style=\"font-weight: bold;\"> 수량 /개 </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t");

										if(order == null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <th><button type=\"button\" class=\"btn btn-inverse-danger btn-rounded btn-icon\" id=\"deleteItem\" onclick=\"deleteCheckedItem();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-delete-forever\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t   </thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t   ");

										if(order != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: 400;\">");
      out.print( order.getpCode() );
      out.write("</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: 400;\">");
      out.print( product.getpName() );
      out.write("</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"font-weight: 400;\">");
      out.print( order.getoAmount() );
      out.write("</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t   </tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  \t  <div class=\"form-group\"> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"shop\">주문매장</label>\r\n");
      out.write("\t\t\t\t\t\t\t");

								if(order != null) 
								{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\"class=\"form-control kor\" value=\"");
      out.print( shop.getsName() );
      out.write("\" disabled >\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
								else
								{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  <select class=\"form-control\" name=\"shop\" id=\"shop\" onchange=\"selectCenter();\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected>매장을 선택하세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S001\">코엑스 별마당</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S002\">압구정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S003\">강남오거리</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S004\">강남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S005\">한티역</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S006\">도산가로수길</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S007\">수원시청</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S008\">수원성균관대</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S009\">범계역</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S010\">킨텍스이마트</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled>-----------</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S011\">대구수목원</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S012\">대구동천</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S013\">경북대</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S014\">부산대연역</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S015\">수영강변</option>\r\n");
      out.write("\t\t\t\t\t\t\t  </select>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"center\">출고센터</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"center\" name=\"center\" class=\"form-control\" placeholder=\"주문매장을 선택하세요.\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.print( cName );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"kor\"><strong>비고</strong></th>\r\n");
      out.write("\t\t\t\t\t\t<td><textarea class=\"form-control\" name=\"comment\" id=\"comment\" cols=\"30\" rows=\"10\" placeholder=\"메모를 입력하세요.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  ");
      out.print( order != null ? "disabled" : "" );
      out.write('>');
      out.write(' ');
      out.print( order != null ? (order.getoComment() == null ? "" : order.getoComment()) : "" );
      out.write(" </textarea></td>\r\n");
      out.write("\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-body\" style=\"text-align: right;\">\r\n");
      out.write("\t\t\t  <h6 class=\"kor\"><strong style=\"margin-right: 20px;\">작성인 : </strong>  발주담당 <span> ");
      out.print( order != null ? writer.geteName() : empLoggedIn.geteName()  );
      out.write("</span></h6>\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"oWriter\" value=\"");
      out.print( empLoggedIn.geteCode() );
      out.write("\" />\r\n");
      out.write("\t\t\t  <h6 class=\"kor\">");
      out.print( order != null ? sdf.format(order.getoDate()) : today );
      out.write("</h6>\r\n");
      out.write("\t\t\t  <br />\r\n");
      out.write("\t\t\t   <button type=\"submit\" class=\"btn btn-gradient-primary btn-icon-text kor\" style=\"float: right;\"\r\n");
      out.write("\t\t\t   \t\t   onclick=\"return validate();\" ");
      out.print( order != null ? "disabled" : "" );
      out.write(">\r\n");
      out.write("\t\t\t\t<i class=\"mdi mdi-file-check btn-icon-prepend\" ></i> 결재요청 </button>\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("          <!-- content-wrapper ends -->\r\n");
      out.write("          <!-- partial -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- main-panel ends -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- page-body-wrapper ends -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- container-scroller -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<!-- End plugin js for this page -->\r\n");
      out.write("<!-- inject:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/misc.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Custom js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/todolist.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  var topEle = $('#topBtn');\r\n");
      out.write("  var delay = 1000;\r\n");
      out.write("  \r\n");
      out.write("  topEle.on('click', function() {\r\n");
      out.write("    $('html, body').stop().animate({scrollTop: 0}, delay);\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("<!-- End custom js for this page -->");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    /* 선택항목 삭제 */\r\n");
      out.write("    function deleteCheckedItem() {\r\n");
      out.write("    \tlet $selectedItem = $(\".selectOne:checked\").not($(\"selectAll\"));\r\n");
      out.write("    \t$selectedItem.parent().parent().remove(); \r\n");
      out.write("    }\r\n");
      out.write("    /* 전체선택 */\r\n");
      out.write("    function selectAllCheckBox() {\r\n");
      out.write("    \tif($(\"#selectAll\").prop(\"checked\")) {\r\n");
      out.write("    \t\t$(\".selectOne\").prop(\"checked\", true);\r\n");
      out.write("    \t}\r\n");
      out.write("    \telse {\r\n");
      out.write("    \t\t$(\".selectOne\").prop(\"checked\", false);\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* 매장 선택시 자동으로 센터 지정되도록 하는 함수 */\r\n");
      out.write("    function selectCenter() {\r\n");
      out.write("    \tlet $shop = $(\"#shop\").val();\r\n");
      out.write("    \tlet shopNum =parseInt($shop.substring(1, 4));\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(shopNum > 10)\r\n");
      out.write("    \t\t$(\"#center\").val(\"대구센터\");\r\n");
      out.write("    \telse\r\n");
      out.write("    \t\t$(\"#center\").val(\"경기센터\");\r\n");
      out.write("    }\r\n");
      out.write("    /* 수량체크 */\r\n");
      out.write("    function numCheck(e){\r\n");
      out.write("    \tif(e.value == 0) {\r\n");
      out.write("    \t\tif(document.activeElement != e) {\r\n");
      out.write("    \t\t\talert(\"수량을 입력하세요.\");\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\te.select();\r\n");
      out.write("    \t}\r\n");
      out.write("    \telse if(e.value > 100){\r\n");
      out.write("    \t\talert(\"수량은 100박스 이하로 입력해주세요.\");\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* 발주서 작성 완료 */\r\n");
      out.write("    function validate() {\r\n");
      out.write("    \tlet $title = $(\"input[name='title']\");\r\n");
      out.write("    \tlet $amount = $(\"input[name='amount']\");\r\n");
      out.write("    \tlet $center = $(\"input[name='center']\");\r\n");
      out.write("    \t\r\n");
      out.write("   \t\tif($(\"#addProductTable tbody tr\").length == 0) {\r\n");
      out.write("   \t\t\talert(\"상품을 추가하세요.\");\r\n");
      out.write("   \t\t\treturn false;\r\n");
      out.write("   \t\t}\r\n");
      out.write("   \t\t\r\n");
      out.write("    \tfor(let i = 0; i < $amount.length; i++) {\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tif($amount[i].value == \"\") {\r\n");
      out.write("    \t\t\talert(\"수량을 입력하세요.\");\r\n");
      out.write("    \t\t\t$amount[i].select();\r\n");
      out.write("    \t\t\treturn false;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tif($amount[i].value > 100) {\r\n");
      out.write("    \t\t\talert(\"수량을 100개 이하로 입력하세요.\");\r\n");
      out.write("    \t\t\t$amount[i].select();\r\n");
      out.write("    \t\t\treturn false;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tif($shop.val() == \"\") {\r\n");
      out.write("    \t\talert(\"매장을 선택하세요.\");\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \treturn true;\r\n");
      out.write("    };\r\n");
      out.write("    \r\n");
      out.write("    /* 상품코드로 검색해서 테이블에 추가하기 */\r\n");
      out.write("    $(\"#addProductBtn\").click(function(){\r\n");
      out.write("    \tlet inp = $(\"#addProductInput\").val();\r\n");
      out.write("    \tif(inp == \"\") {\r\n");
      out.write("    \t\talert(\"상품코드를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print( contextPath );
      out.write("/order/searchPname\",\t\t\r\n");
      out.write("\t\t\tdata:{pCode:inp},\t\r\n");
      out.write("\t\t\ttype:\"get\",\t\t\t\r\n");
      out.write("\t\t\tsuccess:function(pList){ \r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 통신 성공!\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet result = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(pList.length == 0)\r\n");
      out.write("\t\t\t\t\talert(\"조회된 상품이 없습니다.\");\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\tfor(let i = 0; i < pList.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t/* 중복제거 */\r\n");
      out.write("\t\t\t\t\t\tlet arr = [];\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.each($(\"input[name='pCode']\"),function(k,v) {\r\n");
      out.write("\t\t\t\t            arr[arr.length] = $(v).val();\r\n");
      out.write("\t\t\t\t         })\r\n");
      out.write("\t\t\t\t         \r\n");
      out.write("\t\t\t\t         if(arr.includes(pList[i].pCode)) {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t         else {\r\n");
      out.write("\t\t\t\t\t         /* 중복되지 않는 행 추가 */\r\n");
      out.write("\t\t\t\t\t\t\tresult += \"<tr>\" +\r\n");
      out.write("\t\t\t\t\t\t\t\t      \"<td style='padding: 0 3%; width: 11%;'><input type='checkbox' class='selectOne'></td>\" +\r\n");
      out.write("\t\t\t\t\t\t\t\t      \"<td style='padding: 0;'><input type='text' name='pCode' style='padding: 0; width: 100%; display: inline-block; border: none;' value='\" + pList[i].pCode + \"' readonly></td>\" +\r\n");
      out.write("\t\t\t\t\t\t\t\t      \"<td>\" + pList[i].pName + \"</td>\" +\r\n");
      out.write("\t\t\t\t\t\t\t\t      \"<td style='width: 100%;'><input type='number' class='form-control' name='amount' style='height: 1.875rem;' onblur='numCheck(this)'></td>\" +\r\n");
      out.write("\t\t\t\t\t\t\t\t      \"</tr>\";\r\n");
      out.write("\t\t\t\t         }\r\n");
      out.write("\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#addProductTable tbody\").append(result);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(){\t\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 통신 실패!\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete:function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
