/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-11 07:44:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import order.model.vo.Transfer;
import product.model.vo.Product;

public final class transferFinder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/order/../common/navbar.jsp", Long.valueOf(1594042180000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/footer.jsp", Long.valueOf(1594349126593L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/footerScript.jsp", Long.valueOf(1594450848036L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/header.jsp", Long.valueOf(1593330696000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/meta.jsp", Long.valueOf(1593265000000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/sidebar.jsp", Long.valueOf(1594368006940L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("order.model.vo.Transfer");
    _jspx_imports_classes.add("product.model.vo.Product");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String contextPath = request.getContextPath();
	List<Transfer> list = (List<Transfer>) request.getAttribute("list");
	Product p = (Product) request.getAttribute("product");
	String pageBar = (String) request.getAttribute("pageBar");
	String searchType = request.getParameter("searchType");
	String searchKeyword = request.getParameter("searchKeyword");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/js/jquery-3.5.1.js\"></script>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
      out.write("\n");
      out.write("<title>이송</title>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/css/style.css\">\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/favicon.png\" />\r\n");
      out.write("<!-- font 적용-->\r\n");
      out.write("<!-- 한글 폰트 적용 : 해당 태그 클래스에 'kor' 기입 -->\r\n");
      out.write("<!-- font-family: 'Noto Sans KR', sans-serif; -->\r\n");
      out.write("<!-- font-weight은 100, 300, 400(default), 500, 700, 900 가능합니다. -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.kor {\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t\tcolor: #343A40;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("    .popup_panel { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 100;}\n");
      out.write("    .popup_panel div.popup_bg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; background:#000; opacity:.5; filter:alpha(opacity=50); }\n");
      out.write("    .popup_panel div.popup_contents { position: absolute; top: 30%; left: 50%; width:600px; hight:800px; border:2px solid #b66dff; background-color:#fff; }\n");
      out.write("    .popup_contents2 {display:inline; float: right; margin: 30px; margin-top: 90px; margin-right: 30px;}\n");
      out.write("    td,th,tr {text-align:center;}\n");
      out.write("    div#pageBar{margin-top:20px; text-align:center;}\n");
      out.write("\tdiv#pageBar span.cPage{font-weight:bold; color: #b66dff; margin-right: 5px; font-size:15px}\n");
      out.write("\tdiv#pageBar a{margin-right: 5px; font-size:15px}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"container-scroller\">\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_navbar.html -->\r\n");
      out.write("<nav class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("  <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("    <a class=\"navbar-brand brand-logo\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo.png\" alt=\"logo\" /></a>\r\n");
      out.write("    <a class=\"navbar-brand brand-logo-mini\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo-mini.svg\" alt=\"logo\" /></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler align-self-center\" type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"search-field d-none d-md-block\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("      <li class=\"nav-item nav-profile dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <div class=\"nav-profile-text\">\r\n");
      out.write("            <p class=\"mb-1 text-black\">David Greymaax</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-lg-block full-screen-link\">\r\n");
      out.write("        <a class=\"nav-link\">\r\n");
      out.write("          <i class=\"mdi mdi-fullscreen\" id=\"fullscreen-button\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\t  <li class=\"nav-item dropdown\">\r\n");
      out.write("\t    <a class=\"nav-link count-indicator dropdown-toggle\" id=\"messageDropdown\" href=\"#\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t  \t<i class=\"mdi mdi-email-outline\"></i>\r\n");
      out.write("\t  \t<span class=\"count-symbol bg-warning\"></span>\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\" aria-labelledby=\"messageDropdown\">\r\n");
      out.write("\t  \t<h6 class=\"p-3 mb-0\">Messages</h6>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t  \t  <div class=\"preview-thumbnail\">\r\n");
      out.write("\t  \t\t<img src=\"assets/images/faces/face4.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("\t  \t\t<h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Mark send you a message</h6>\r\n");
      out.write("\t  \t\t<p class=\"text-gray mb-0\"> 1 Minutes ago </p>\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t</a>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t  \t  <div class=\"preview-thumbnail\">\r\n");
      out.write("\t  \t\t<img src=\"assets/images/faces/face2.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("\t  \t\t<h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Cregh send you a message</h6>\r\n");
      out.write("\t  \t\t<p class=\"text-gray mb-0\"> 15 Minutes ago </p>\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t</a>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t  \t  <div class=\"preview-thumbnail\">\r\n");
      out.write("\t  \t\t<img src=\"assets/images/faces/face3.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("\t  \t\t<h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Profile picture updated</h6>\r\n");
      out.write("\t  \t\t<p class=\"text-gray mb-0\"> 18 Minutes ago </p>\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t</a>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<h6 class=\"p-3 mb-0 text-center\">4 new messages</h6>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </li>\r\n");
      out.write("      <li class=\"nav-item nav-logout d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("          <i class=\"mdi mdi-power\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item nav-settings d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("          <i class=\"mdi mdi-format-line-spacing\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\n");
      out.write("    <!-- partial -->\n");
      out.write("    <div class=\"container-fluid page-body-wrapper\">\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("  <ul class=\"nav\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"index.jsp\">\r\n");
      out.write("        <span class=\"menu-title kor\">메 인</span>\r\n");
      out.write("        <i class=\"mdi mdi-home menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#product\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">상품관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-basket menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"product\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/warehousing\">입고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/beReleased\">출고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/stk\">재고</a></li> ");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#order\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">거래관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-barcode-scan menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"order\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/ordr\">발주</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/transfer\">이송</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#sales\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">매출관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-chart-line menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"sales\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item kor\"> <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/sales\">통계</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#approval\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">전자결재</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-script menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"approval\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item kor\"> <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/approval\">결재관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>");
      out.write("\n");
      out.write("      <!-- partial -->\n");
      out.write("      <div class=\"main-panel\">\n");
      out.write("        <div class=\"content-wrapper\">\n");
      out.write("            <i class=\"mdi mdi-close\" id=\"bannerClose\" style=\"display: none;\"></i>\n");
      out.write("           <div class=\"page-header\" style=\"width: 100%\">\n");
      out.write("          \t<div style=\"display: inline-block; width: 50%; text-align: left;\">\n");
      out.write("             <h3 class=\"page-title kor\" style=\"display: inline-block; margin-right: 25px;\">\n");
      out.write("               <span class=\"page-title-icon bg-gradient-primary text-white mr-2\">\n");
      out.write("                 <i class=\"mdi mdi-barcode-scan\"></i>\n");
      out.write("               </span> 이 송 </h3>\n");
      out.write("          \t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("        ");
      out.write("\n");
      out.write("        \n");
      out.write(" <div class=\"col-12\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <form action=\"");
      out.print(contextPath );
      out.write("/order/transferFinder\" class=\"form-sample\">\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label\">이송코드</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-tCode\">\n");
      out.write("                          <input type=\"text\" class=\"form-control\" name=\"searchKeyword\"/>\n");
      out.write("                          <input type=\"hidden\" class=\"form-control\" name=\"searchType\" value=\"tCode\"/>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label\">상품코드</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-pCode\">\n");
      out.write("                          <input type=\"text\" class=\"form-control\" name=\"searchKeyword\"/>\n");
      out.write("                          <input type=\"hidden\" class=\"form-control\" name=\"searchType\" value=\"pCode\"/>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label\">출발센터</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-depCode\">\n");
      out.write("                          <select class=\"form-control\">\n");
      out.write("                            <option name=\"searchKeyword\" id=\"depCode_GG\" value=\"GG\">광주센터</option>\n");
      out.write("                            <option name=\"searchKeyword\" id=\"depCode_DG\" value=\"DG\">대구센터</option>\n");
      out.write("                          </select>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label\">도착센터</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-depCode\">\n");
      out.write("                          <select class=\"form-control\">\n");
      out.write("                            <option name=\"searchKeyword\" id=\"desCode_GG\" value=\"GG\">광주센터</option>\n");
      out.write("                            <option name=\"searchKeyword\" id=\"desCode_DG\" value=\"DG\">대구센터</option>\n");
      out.write("                          </select>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label\">기간</label>\n");
      out.write("                        <div class=\"col-sm-9\">\n");
      out.write("                         <input type=\"date\" class=\"form-control\" id=\"dateSearch\"/>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\" >\n");
      out.write("                        <label class=\"col-sm-3 col-form-label\" style=\"text-align: center\"> - </label>\n");
      out.write("                        <div class=\"col-sm-9\">\n");
      out.write("                         <input type=\"date\" class=\"form-control\" />\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                     <button type=\"submit\" class=\"btn btn-inverse-primary btn-fw\" style=\"float: right\">Search</button>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-12 grid-margin\" style=\"margin-top: 26px\">\n");
      out.write("           <div class=\"card\">\n");
      out.write("             <div class=\"card-body\">\n");
      out.write("               <!-- <h4 class=\"card-title\">발주 리스트</h4> -->\n");
      out.write("               <div class=\"table-responsive\">\n");
      out.write("                 <table class=\"table\">\n");
      out.write("                   <thead>\n");
      out.write("                   <style>\n");
      out.write("                   #stock-tr{\n");
      out.write("                   \t/* font-family: 고딕; */\n");
      out.write("                   \tfont-weight: bold;\n");
      out.write("                   }\n");
      out.write("                   </style>\n");
      out.write("                     <tr>\n");
      out.write("                       <th><strong>이송코드</strong></th>\n");
      out.write("            <th><strong>상품코드</strong></th>\n");
      out.write("            <th><strong>품의코드</strong></th>\n");
      out.write("            <th><strong>입고/출고/이송 여부</strong></th>\n");
      out.write("            <th><strong>출발지코드</strong></th>\n");
      out.write("            <th><strong>도착지코드</strong></th>\n");
      out.write("            <th><strong>이송수량 (BOX)</strong></th>\n");
      out.write("            <th><strong>이송일</strong></th>\n");
      out.write("                     </tr>\n");
      out.write("                   </thead>\n");
      out.write("                   ");
if(list == null || list.isEmpty()) { 
      out.write("\n");
      out.write("                   <!-- 조회된 행이 없는 경우 -->\n");
      out.write("                   <tr>\n");
      out.write("                   \t<th colspan=\"6\" style=\"text-align:center\">조회된 행이 없습니다.</th>\n");
      out.write("                   </tr>\n");
      out.write("                   ");
} else { 
                   		for(Transfer f : list) {
                   
      out.write("\n");
      out.write("                   <!-- 조회된 행이 있는 경우 -->\n");
      out.write("                   <!-- 가상테이블 -->\n");
      out.write("          <tr>\n");
      out.write("            <td>");
      out.print( f.gettCode() );
      out.write("</td>\n");
      out.write("            <td>\n");
      out.write("            <a href=\"javascript:void(0)\" id=\"btn_popup_open\">\n");
      out.write("             ");
      out.print(f.getpCode() );
      out.write("\n");
      out.write("            </a>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("            <a href=\"\" onclick=\"window.open('");
      out.print( contextPath );
      out.write("/approval/approvalView?aCode=");
      out.print(f.getaCode() );
      out.write("',\n");
      out.write("\t\t            \t\t\t'_blank', 'top=300,left=500,width=800,height=1000')\">\n");
      out.write("\t\t            \t\t\t\n");
      out.write("             ");
      out.print(f.getaCode() );
      out.write("\n");
      out.write("             \n");
      out.write("            </a>\n");
      out.write("           </td>\n");
      out.write("            <td id=\"status\">\n");
      out.write("            ");
if (f.gettStatus().equals("WAREHOUSING")) {
      out.write("\n");
      out.write("            \t<label class=\"badge badge-gradient-info\">입고</label>\n");
      out.write("            \t");
} else if (f.gettStatus().equals("BE_RELEASED")){
      out.write("\n");
      out.write("            \t<label class=\"badge badge-gradient-danger\">출고</label>\n");
      out.write("            \t");
} else if (f.gettStatus().equals("TRANSFER_WAREHOUSING")){
      out.write("\n");
      out.write("            \t<label class=\"badge badge-gradient-warning\">이송</label>\n");
      out.write("            \t<label class=\"badge badge-gradient-info\">입고</label>\n");
      out.write("            \t");
} else {
      out.write(" \n");
      out.write("            \t<label class=\"badge badge-gradient-warning\">이송</label>\n");
      out.write("            \t<label class=\"badge badge-gradient-danger\">출고</label>\n");
      out.write("            ");
}
      out.write("\n");
      out.write("            </td>\n");
      out.write("            \n");
      out.write("            <!-- 이렇게 하면 첫행만 추가됨.. -->\n");
      out.write("           ");
      out.write("\n");
      out.write("            \n");
      out.write("            <td data-toggle=\"tooltip\" data-placement=\"top\"\n");
      out.write("            \ttitle=");
      out.print(f.getDepartureCode().equals("DG") ? "대구센터" : "경기"+"광주센터" );
      out.write(">\n");
      out.write("            \t");
      out.print(f.getDepartureCode() );
      out.write("</td>\n");
      out.write("            \t\n");
      out.write("            <td data-toggle=\"tooltip\" data-placement=\"top\"\n");
      out.write("            \ttitle=");
      out.print(f.getDestinationCode().equals("DG") ? "대구센터" : "경기"+"광주센터" );
      out.write(">\n");
      out.write("            \t");
      out.print(f.getDestinationCode() );
      out.write("</td>\n");
      out.write("            \t\n");
      out.write("            <td>");
      out.print(f.gettAmount() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print(f.gettDate() );
      out.write("</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("        \n");
      out.write("        ");
 }
}
      out.write("\n");
      out.write("                 </table>\n");
      out.write("                 <!-- 페이징처리 -->\n");
      out.write("                 \t<div id='pageBar'>\n");
      out.write("                 \t");
      out.print( request.getAttribute("pageBar") );
      out.write("\n");
      out.write("                  \t</div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("</form>\n");
      out.write("<div class=\"popup_panel\">\n");
      out.write("<div class=\"popup_bg\"></div>\n");
      out.write("         <div class=\"popup_contents\" style=\"float: left;\">\n");
      out.write("        <img src=\"../images/MUG-01.jpg\" alt=\"\" />\n");
      out.write("       \t<div class=\"popup_contents2\">\n");
      out.write("       \t<span>[MUG]</span>\n");
      out.write("       \t<span>헤리티지 핸들 머그 355ml</span>\n");
      out.write("       \t<hr />\n");
      out.write("       \t<span style=\"float:right\">18000원</span>\n");
      out.write("       \t</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("      <!-- content-wrapper ends -->\n");
      out.write("\t   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_footer.html -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("    <span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright © 2017 <a href=\"#\" target=\"_blank\">STOCKer</a>. All rights reserved.</span>\r\n");
      out.write("    <i class=\"mdi mdi-heart text-danger\" id=\"topBtn\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\n");
      out.write("      <!-- partial -->\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- main-panel ends -->\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <!-- page-body-wrapper ends -->\n");
      out.write("</div>\n");
      out.write("<!-- container-scroller -->\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<!-- End plugin js for this page -->\r\n");
      out.write("<!-- inject:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/misc.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Custom js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/todolist.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  var topEle = $('#topBtn');\r\n");
      out.write("  var delay = 1000;\r\n");
      out.write("  \r\n");
      out.write("  topEle.on('click', function() {\r\n");
      out.write("    $('html, body').stop().animate({scrollTop: 0}, delay);\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("<!-- End custom js for this page -->");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t// 센터명 호버했을때 한글설명나오게하기\n");
      out.write("\t$('[data-toggle=\"tooltip\"]').tooltip();\n");
      out.write("\t\n");
      out.write("\t// 레이어팝업 \n");
      out.write("    var $panel = $(\".popup_panel\");\n");
      out.write("    var $panelContents = $panel.find(\".popup_contents\");\n");
      out.write("    $(\"#btn_popup_open\").on(\"click\", function(e) {\n");
      out.write("\n");
      out.write("        // 팝업 가운데 설정(가로)\n");
      out.write("        if ($panelContents.outerWidth() < $(document).width()) {\n");
      out.write("            $panelContents.css(\"margin-left\", \"-\" + $panelContents.outerWidth() / 2 + \"px\");\n");
      out.write("        } else {\n");
      out.write("            $panelContents.css(\"left\", \"0px\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // 팝업 가운데 설정(세로)\n");
      out.write("        if ($panelContents.outerHeight() < $(document).height()) {\n");
      out.write("            $panelContents.css(\"margin-top\", \"-\" + $panelContents.outerHeight() / 2 + \"px\");\n");
      out.write("        } else {\n");
      out.write("            $panelContents.css(\"top\", \"0px\");\n");
      out.write("        }\n");
      out.write("        // 레이어 팝업 열기\n");
      out.write("        $panel.fadeIn();\n");
      out.write("    });\n");
      out.write("    // 팝업 닫기 이벤트 정의\n");
      out.write("    $(\"#btn_popup_close\").on(\"click\", popupClose);\n");
      out.write("\n");
      out.write("    // 팝업 배경 클릭 이벤트 정의\n");
      out.write("    $panel.find(\".popup_bg\").on(\"click\", popupClose);\n");
      out.write("\n");
      out.write("function popupClose(e) {\n");
      out.write("    $panel.fadeOut();\n");
      out.write("    // 이벤트 기본 동작 중단\n");
      out.write("    e.preventDefault();\n");
      out.write("}\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
