/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-19 08:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import order.model.vo.Transfer;
import product.model.vo.Product;
import member.model.vo.Employee;
import member.model.service.EmpService;
import member.model.vo.Employee;

public final class transfer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/order/../common/navbar.jsp", Long.valueOf(1595144081730L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/footer.jsp", Long.valueOf(1594349126000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/footerScript.jsp", Long.valueOf(1594450848000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/header.jsp", Long.valueOf(1593330696000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/meta.jsp", Long.valueOf(1593265000000L));
    _jspx_dependants.put("/WEB-INF/views/order/../common/sidebar.jsp", Long.valueOf(1595039526000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("order.model.vo.Transfer");
    _jspx_imports_classes.add("product.model.vo.Product");
    _jspx_imports_classes.add("member.model.vo.Employee");
    _jspx_imports_classes.add("member.model.service.EmpService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String contextPath = request.getContextPath();
	
	List<Transfer> transferList = (List<Transfer>) request.getAttribute("transferList");
	Product product = (Product) request.getAttribute("product");
	String pageBar = (String) request.getAttribute("pageBar");
	String msg = (String) session.getAttribute("msg");
	

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/js/jquery.qrcode.js\"></script>\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/js/qrcode.js\"></script>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
      out.write("\n");
      out.write("<title>이송</title>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/css/style.css\">\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/favicon.png\" />\r\n");
      out.write("<!-- font 적용-->\r\n");
      out.write("<!-- 한글 폰트 적용 : 해당 태그 클래스에 'kor' 기입 -->\r\n");
      out.write("<!-- font-family: 'Noto Sans KR', sans-serif; -->\r\n");
      out.write("<!-- font-weight은 100, 300, 400(default), 500, 700, 900 가능합니다. -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.kor {\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t\tcolor: #343A40;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("    .popup_panel { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 100;}\n");
      out.write("    .popup_panel div.popup_bg { position: absolute; top: 0; left: 0; width: 100%; height: 100%; background:#000; opacity:.5; filter:alpha(opacity=50); }\n");
      out.write("    .popup_panel div.popup_contents { position: absolute; top: 30%; left: 50%; width:600px; hight:800px; border:2px solid #b66dff; background-color:#fff; }\n");
      out.write("    .popup_contents2 {display:inline; float: right; margin: 30px; margin-top: 63px; margin-right: 38px;}\n");
      out.write("    td,th,tr {text-align:center;}\n");
      out.write("    div#pageBar{margin-top:20px; text-align:center;}\n");
      out.write("\tdiv#pageBar span.cPage{font-weight:bold; color: #b66dff; margin-right: 5px; font-size:15px}\n");
      out.write("\tdiv#pageBar a{margin-right: 5px; font-size:15px}\n");
      out.write("\t\n");
      out.write("\t.stock-tr{\n");
      out.write("\t\tfont-family: \"고딕\";\n");
      out.write("\t\tfont-weight: bold;\n");
      out.write("\t}\n");
      out.write("\ta {\n");
      out.write("\tcolor:#b66dff;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");

  	if(msg != null && !msg.equals(""))
  	{
  
      out.write("\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\talert(\"");
      out.print( msg );
      out.write("\"); \n");
      out.write("\t\t</script>\n");
      out.write("  ");

  		session.removeAttribute("msg");
  	}
  
      out.write("\n");
      out.write("  <div class=\"container-scroller\">\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
 
	Employee empLoggedIn = (Employee) session.getAttribute("empLoggedIn");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_navbar.html -->\r\n");
      out.write("<nav class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("  <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("    <a class=\"navbar-brand brand-logo\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo.png\" alt=\"logo\" /></a>\r\n");
      out.write("    <a class=\"navbar-brand brand-logo-mini\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo-mini.svg\" alt=\"logo\" /></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler align-self-center\" type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"search-field d-none d-md-block\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("      <li class=\"nav-item nav-profile dropdown\" style=\"margin-top: 2%;\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <div class=\"nav-profile-text\" >\r\n");
      out.write("          ");
if(empLoggedIn != null){
      out.write("\r\n");
      out.write("          <p class=\"mb-1 text-black\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/infoView?eCode=");
      out.print(empLoggedIn.geteCode());
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(empLoggedIn.geteDept());
      out.write(" <strong>");
      out.print(empLoggedIn.geteName() );
      out.write("</strong></p>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-lg-block full-screen-link\">\r\n");
      out.write("        <a class=\"nav-link\">\r\n");
      out.write("          <i class=\"mdi mdi-fullscreen\" id=\"fullscreen-button\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\t  <li class=\"nav-item\">\r\n");
      out.write("\t    <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath());
      out.write("/board/boardList\">\r\n");
      out.write("\t  \t<i class=\"mdi mdi-bulletin-board\"></i>\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t  </li>\r\n");
      out.write("      <li class=\"nav-item nav-logout d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("          <i class=\"mdi mdi-power\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item nav-settings d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("          <i class=\"mdi mdi-format-line-spacing\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\n");
      out.write("    <!-- partial -->\n");
      out.write("    <div class=\"container-fluid page-body-wrapper\">\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Employee user = (Employee) session.getAttribute("empLoggedIn");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("  <ul class=\"nav\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("\">\r\n");
      out.write("        <span class=\"menu-title kor\">메 인</span>\r\n");
      out.write("        <i class=\"mdi mdi-home menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#product\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">상품관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-basket menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"product\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/warehousing?currentPage=1\">입고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/beReleased\">출고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/stk\">재고</a></li> \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#order\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">거래관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-barcode-scan menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"order\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/ordr?currentPage=1\">발주</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/transfer\">이송</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("       <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/sales\">\r\n");
      out.write("        <span class=\"menu-title kor\">통 계</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-chart-line menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/approval?currentPage=1\">\r\n");
      out.write("        <span class=\"menu-title kor\">결재진행</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-script menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>");
      out.write("\n");
      out.write("      <!-- partial -->\n");
      out.write("      <div class=\"main-panel\">\n");
      out.write("        <div class=\"content-wrapper\">\n");
      out.write("            <i class=\"mdi mdi-close\" id=\"bannerClose\" style=\"display: none;\"></i>\n");
      out.write("           <div class=\"page-header\" style=\"width: 100%\">\n");
      out.write("          \t<div style=\"display: inline-block; width: 50%; text-align: left;\">\n");
      out.write("             <h3 class=\"page-title kor\" style=\"display: inline-block; margin-right: 25px;\">\n");
      out.write("               <span class=\"page-title-icon bg-gradient-primary text-white mr-2\">\n");
      out.write("                 <i class=\"mdi mdi-car\"></i>\n");
      out.write("               </span> 이 송 </h3>\n");
      out.write("          \t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("        ");
      out.write("\n");
      out.write("        \n");
      out.write(" <div class=\"col-12\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <form action=\"");
      out.print(contextPath );
      out.write("/order/transferSearch\" id=\"searchForm\" class=\"form-sample\">\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label stock-tr\">이송코드</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-tCode\">\n");
      out.write("                          <input type=\"text\" class=\"form-control\" name=\"search\" id=\"search_tcode\"/>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label stock-tr\">상품코드</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-pCode\">\n");
      out.write("                          <input type=\"text\" class=\"form-control\" name=\"search\" id=\"search_pcode\"/>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label stock-tr\">출발센터</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-depCode\">\n");
      out.write("                          <select class=\"form-control center-name\" name=\"search\" form=\"searchForm\" id=\"dep_name\">\n");
      out.write("                            <option selected ></option>\n");
      out.write("                            <option value=\"GG\">광주센터</option>\n");
      out.write("                            <option value=\"TK\">대구센터</option>\n");
      out.write("                          </select>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label stock-tr\">도착센터</label>\n");
      out.write("                        <div class=\"col-sm-9\" id=\"search-depCode\">\n");
      out.write("                          <select class=\"form-control center-name\" name=\"search\" form=\"searchForm\" id=\"des_name\">\n");
      out.write("                           <option selected></option>\n");
      out.write("                           <option value=\"GG\">광주센터</option>\n");
      out.write("                            <option value=\"TK\">대구센터</option>\n");
      out.write("                          </select>\n");
      out.write("                          \n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\">\n");
      out.write("                        <label class=\"col-sm-3 col-form-label stock-tr\">기간</label>\n");
      out.write("                        <div class=\"col-sm-9\">\n");
      out.write("                         <input type=\"date\" class=\"form-control\" name=\"search\" id=\"search_sdate\"/>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                      <div class=\"form-group row\" >\n");
      out.write("                        <label class=\"col-sm-3 col-form-label stock-tr\" style=\"text-align: center\"> - </label>\n");
      out.write("                        <div class=\"col-sm-9\">\n");
      out.write("                         <input type=\"date\" class=\"form-control\" name=\"search\" id=\"search_edate\"/>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("       \t                 <button type=\"button\" class=\"btn btn-inverse-info btn-fw\" style=\"float: left; font-weight: bold\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/order/transfer'\">전체보기</button>\n");
      out.write("                     </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                     <button type=\"submit\" class=\"btn btn-inverse-primary btn-fw\" style=\"float: right\" >Search</button>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-12 grid-margin\" style=\"margin-top: 26px\">\n");
      out.write("           <div class=\"card\">\n");
      out.write("             <div class=\"card-body\">\n");
      out.write("               <div class=\"table-responsive\">\n");
      out.write("                 <table class=\"table\">\n");
      out.write("                   <thead>\n");
      out.write("                     <tr>\n");
      out.write("                       <th><strong>이송코드</strong></th>\n");
      out.write("            <th><strong>상품코드</strong></th>\n");
      out.write("            <th><strong>출고센터</strong></th>\n");
      out.write("            <th></th>\n");
      out.write("            <th><strong>입고센터</strong></th>\n");
      out.write("            <th><strong>이송수량 (개)</strong></th>\n");
      out.write("            <th><strong>이송일</strong></th>\n");
      out.write("                     </tr>\n");
      out.write("                   </thead>\n");
      out.write("                   ");
if(transferList == null || transferList.isEmpty()) { 
      out.write("\n");
      out.write("                   <!-- 조회된 행이 없는 경우 -->\n");
      out.write("                   <tr>\n");
      out.write("                   \t<th colspan=\"7\" style=\"text-align:center\">조회된 행이 없습니다.</th>\n");
      out.write("                   </tr>\n");
      out.write("                   ");
} else { 
                   		for(Transfer t : transferList) {
                   
      out.write("\n");
      out.write("                   <!-- 조회된 행이 있는 경우 -->\n");
      out.write("          <tr>\n");
      out.write("            <td><a href=\"#\" onclick=\"window.open('");
      out.print( contextPath );
      out.write("/order/transferView?tCode=");
      out.print(t.gettCode() );
      out.write("',\n");
      out.write("\t\t            \t\t\t'_blank','top=1,left=500,width=1000,height=700')\">");
      out.print( t.gettCode() );
      out.write("</a></td>\n");
      out.write("            <td>\n");
      out.write("            <a href=\"javascript:void(0)\" class=\"btn_popup_open\">\n");
      out.write("             ");
      out.print(t.getpCode() );
      out.write("\n");
      out.write("            </a>\n");
      out.write("            </td>\n");
      out.write("            ");
      out.write("\n");
      out.write("            \n");
      out.write("            <td data-toggle=\"tooltip\" data-placement=\"top\"\n");
      out.write("            \ttitle=");
      out.print(t.getDepartureCode().equals("TK") ? "대구센터" : "경기"+"광주센터" );
      out.write(">\n");
      out.write("            \t\n");
      out.write("            \t");
if(t.getDepartureCode().equals("TK")) {
      out.write(" \n");
      out.write("            \t\t<label class=\"badge badge-gradient-info\">대구</label>\n");
      out.write("            \t");
} else { 
      out.write("\n");
      out.write("            \t\t<label class=\"badge badge-gradient-danger\">경기광주</label>\n");
      out.write("            \t");
 } 
      out.write("\n");
      out.write("            \t</td>\n");
      out.write("            \t<!-- 화살표 시작 -->\n");
      out.write("            \t<td> <i class=\"mdi mdi-chevron-double-right\"></i> </td>\n");
      out.write("            \t<!-- 화살표 끝 -->\n");
      out.write("             <td data-toggle=\"tooltip\" data-placement=\"top\"\n");
      out.write("            \ttitle=");
      out.print(t.getDestinationCode().equals("TK") ? "대구센터" : "경기"+"광주센터" );
      out.write(">\n");
      out.write("            \t\n");
      out.write("            \t");
if(t.getDestinationCode().equals("TK")) {
      out.write(" \n");
      out.write("            \t\t<label class=\"badge badge-gradient-info\">대구</label>\n");
      out.write("            \t");
} else { 
      out.write("\n");
      out.write("            \t\t<label class=\"badge badge-gradient-danger\">경기광주</label>\n");
      out.write("            \t");
 } 
      out.write("\n");
      out.write("            \t</td>\n");
      out.write("            \t\n");
      out.write("            <td>");
      out.print(t.gettAmount());
      out.write("</td>\n");
      out.write("            <td>");
      out.print(t.gettDate() );
      out.write("</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("        \n");
      out.write("        ");
 }
}
      out.write("\n");
      out.write("                 </table>\n");
      out.write("                 <!-- 페이징처리 -->\n");
      out.write("                 \t<div id='pageBar'>\n");
      out.write("                 \t");
      out.print( request.getAttribute("pageBar") );
      out.write("\n");
      out.write("                  \t</div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<!-- 레이어 팝업 시작 -->\n");
      out.write("<div class=\"popup_panel\">\n");
      out.write("<div class=\"popup_bg\"></div>\n");
      out.write("<div class=\"popup_contents\" style=\"float: left;\">\n");
      out.write("\t<!-- images/...jpg로 저장 -->\n");
      out.write("\t<img id=\"p_image\" src=\"\" alt=\"\" />\n");
      out.write("\t<div class=\"popup_contents2\">\n");
      out.write("\t<!-- product : p_theme --> \n");
      out.write("\t<span id=\"p_theme\"> </span>\n");
      out.write("\t<!-- product : p_category -->\n");
      out.write("\t<span id=\"p_category\"> </span>\n");
      out.write("\t<!-- product : p_name-->\n");
      out.write("\t<span id=\"p_name\"> </span>\n");
      out.write("\t<hr />\n");
      out.write("\t<!-- product : p_price -->\n");
      out.write("\t<span id=\"p_price\" style=\"float:right\"> </span>\n");
      out.write("\t<!-- qrcode-->\n");
      out.write("\t<div id=\"qrDiv\" style=\"float: right; margin-top: 40px\">\n");
      out.write("\t<img id=\"p_qr_image\" src=\"\" alt=\"\" style=\"width:130px; margin-right: -60px;\"/>\n");
      out.write("\t</div>\n");
      out.write("   \t</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- 레이어 팝업 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- content-wrapper ends -->\n");
      out.write("\t   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_footer.html -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("    <span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright © 2017 <a href=\"#\" target=\"_blank\">STOCKer</a>. All rights reserved.</span>\r\n");
      out.write("    <i class=\"mdi mdi-heart text-danger\" id=\"topBtn\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\n");
      out.write("      <!-- partial -->\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- main-panel ends -->\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <!-- page-body-wrapper ends -->\n");
      out.write("</div>\n");
      out.write("<!-- container-scroller -->\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<!-- End plugin js for this page -->\r\n");
      out.write("<!-- inject:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/misc.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Custom js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/todolist.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  var topEle = $('#topBtn');\r\n");
      out.write("  var delay = 1000;\r\n");
      out.write("  \r\n");
      out.write("  topEle.on('click', function() {\r\n");
      out.write("    $('html, body').stop().animate({scrollTop: 0}, delay);\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("<!-- End custom js for this page -->");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t\n");
      out.write("\t//검색눌렀을때 검색어유지 \n");
      out.write("\tvar searchs = [\n");
      out.write("\t\t 'search_tcode'\n");
      out.write("\t\t,'search_pcode'\n");
      out.write("\t\t,'dep_name'\n");
      out.write("\t\t,'des_name'\n");
      out.write("\t\t,'search_sdate'\n");
      out.write("\t\t,'search_edate'\n");
      out.write("\t\t];\n");
      out.write("\t\n");
      out.write("\tvar url = unescape(location.href); //현재 주소 decoding\n");
      out.write("    var paramArr = (url.substring(url.indexOf(\"?\")+1,url.length)).split(\"&\"); //파라미터만 자르고, 다시 &구분자로 잘라서 배열에 넣는다.\n");
      out.write("    \n");
      out.write("    for(var i = 0 ; i < paramArr.length ; i++){\n");
      out.write("        var temp = paramArr[i].split(\"=\"); //파라미터 변수명을 담음\n");
      out.write("        $(\"#\"+searchs[i]).val(temp[1]); \n");
      out.write("    }\n");
      out.write("\t\n");
      out.write("\t// 센터명 호버했을때 한글설명나오게하기\n");
      out.write("\t$('[data-toggle=\"tooltip\"]').tooltip();\n");
      out.write("\t\n");
      out.write("\t/*********** 레이어팝업 함수 시작 ***********/\n");
      out.write("    var $panel = $(\".popup_panel\");\n");
      out.write("    var $panelContents = $panel.find(\".popup_contents\");\n");
      out.write("    \n");
      out.write("    //상품상세팝업 클릭했을때\n");
      out.write("    $(\".btn_popup_open\").on(\"click\", function(e) {\n");
      out.write("    \tvar pCode = $(this).text();\n");
      out.write("\t\tvar params = {pCode : pCode};\n");
      out.write("\t\tconsole.log(\"request post=\"+\"");
      out.print(contextPath);
      out.write("/order/productDetail\");\n");
      out.write("\t\t$.post('");
      out.print(contextPath);
      out.write("/order/productDetail', $.param(params), function(responseJson){\n");
      out.write("\n");
      out.write("\t\t\tvar obj = $.parseJSON(JSON.stringify(responseJson));\n");
      out.write("\n");
      out.write("\t\t\t$(\"#p_image\").attr(\"src\", obj.pImage);\n");
      out.write("\t\t\t$(\"#p_theme\").text(\"[\" + obj.pTheme + \"]\");\n");
      out.write("\t\t\t$(\"#p_category\").html(\"[\" + obj.pCategory + \"]\" + \"<br>\");\n");
      out.write("\t\t\t$(\"#p_name\").text(obj.pName);\n");
      out.write("\t\t\t$(\"#p_price\").text((obj.pPrice).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\"));\n");
      out.write("\t\t\t$(\"#p_qr_image\").attr(\"src\", obj.pQrImage);\n");
      out.write("\t\t});\n");
      out.write("        // 팝업 가운데 설정(가로)\n");
      out.write("        if ($panelContents.outerWidth() < $(document).width()) {\n");
      out.write("            $panelContents.css(\"margin-left\", \"-\" + $panelContents.outerWidth() / 2 + \"px\");\n");
      out.write("        } else {\n");
      out.write("            $panelContents.css(\"left\", \"0px\");\n");
      out.write("        }\n");
      out.write("        // 팝업 가운데 설정(세로)\n");
      out.write("        if ($panelContents.outerHeight() < $(document).height()) {\n");
      out.write("            $panelContents.css(\"margin-top\", \"-\" + $panelContents.outerHeight() / 2 + \"px\");\n");
      out.write("        } else {\n");
      out.write("            $panelContents.css(\"top\", \"0px\");\n");
      out.write("        }\n");
      out.write("        // 레이어 팝업 열기\n");
      out.write("        $panel.fadeIn();\n");
      out.write("    });\n");
      out.write("    // 팝업 닫기 이벤트 정의\n");
      out.write("    $(\"#btn_popup_close\").on(\"click\", popupClose);\n");
      out.write("    // 팝업 배경 클릭 이벤트 정의\n");
      out.write("    $panel.find(\".popup_bg\").on(\"click\", popupClose);\n");
      out.write("\n");
      out.write("function popupClose(e) {\n");
      out.write("    $panel.fadeOut();\n");
      out.write("    // 이벤트 기본 동작 중단\n");
      out.write("    e.preventDefault();\n");
      out.write("}\n");
      out.write("/*********** 레이어팝업 함수 끝 ***********/\n");
      out.write("\n");
      out.write("//출발센터 도착센터 같은 센터 지정 불가함수 \n");
      out.write("$(\".center-name\").change(function(){\n");
      out.write("\tif($(\"#dep_name option:selected\").val() == $(\"#des_name option:selected\").val()) {\n");
      out.write("\t\talert('출발센터와 도착센터를 같은 곳으로 지정할 수 없습니다.');\n");
      out.write("\t\t$(this).find(\"option:eq(0)\").prop(\"selected\", true);\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
