/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-08 01:20:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.approval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class approval_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/views/approval/../common/navbar.jsp", Long.valueOf(1594042180000L));
    _jspx_dependants.put("/views/approval/../common/meta.jsp", Long.valueOf(1593265000000L));
    _jspx_dependants.put("/views/approval/../common/sidebar.jsp", Long.valueOf(1594043218000L));
    _jspx_dependants.put("/views/approval/../common/footerScript.jsp", Long.valueOf(1593265640000L));
    _jspx_dependants.put("/views/approval/../common/header.jsp", Long.valueOf(1593330696000L));
    _jspx_dependants.put("/views/approval/../common/footer.jsp", Long.valueOf(1593265526000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();

	SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일");
	Date now = new Date();
	String today = sdf.format(now); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("\t ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
      out.write("\r\n");
      out.write("\t <title>결재관리</title>\r\n");
      out.write("\t ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/css/style.css\">\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/favicon.png\" />\r\n");
      out.write("<!-- font 적용-->\r\n");
      out.write("<!-- 한글 폰트 적용 : 해당 태그 클래스에 'kor' 기입 -->\r\n");
      out.write("<!-- font-family: 'Noto Sans KR', sans-serif; -->\r\n");
      out.write("<!-- font-weight은 100, 300, 400(default), 500, 700, 900 가능합니다. -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.kor {\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t\tcolor: #343A40;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container-scroller\">\r\n");
      out.write("\t  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_navbar.html -->\r\n");
      out.write("<nav class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("  <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("    <a class=\"navbar-brand brand-logo\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo.png\" alt=\"logo\" /></a>\r\n");
      out.write("    <a class=\"navbar-brand brand-logo-mini\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/images/logo-mini.svg\" alt=\"logo\" /></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler align-self-center\" type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"search-field d-none d-md-block\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("      <li class=\"nav-item nav-profile dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <div class=\"nav-profile-text\">\r\n");
      out.write("            <p class=\"mb-1 text-black\">David Greymaax</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-lg-block full-screen-link\">\r\n");
      out.write("        <a class=\"nav-link\">\r\n");
      out.write("          <i class=\"mdi mdi-fullscreen\" id=\"fullscreen-button\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\t  <li class=\"nav-item dropdown\">\r\n");
      out.write("\t    <a class=\"nav-link count-indicator dropdown-toggle\" id=\"messageDropdown\" href=\"#\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t  \t<i class=\"mdi mdi-email-outline\"></i>\r\n");
      out.write("\t  \t<span class=\"count-symbol bg-warning\"></span>\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\" aria-labelledby=\"messageDropdown\">\r\n");
      out.write("\t  \t<h6 class=\"p-3 mb-0\">Messages</h6>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t  \t  <div class=\"preview-thumbnail\">\r\n");
      out.write("\t  \t\t<img src=\"assets/images/faces/face4.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("\t  \t\t<h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Mark send you a message</h6>\r\n");
      out.write("\t  \t\t<p class=\"text-gray mb-0\"> 1 Minutes ago </p>\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t</a>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t  \t  <div class=\"preview-thumbnail\">\r\n");
      out.write("\t  \t\t<img src=\"assets/images/faces/face2.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("\t  \t\t<h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Cregh send you a message</h6>\r\n");
      out.write("\t  \t\t<p class=\"text-gray mb-0\"> 15 Minutes ago </p>\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t</a>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t  \t  <div class=\"preview-thumbnail\">\r\n");
      out.write("\t  \t\t<img src=\"assets/images/faces/face3.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("\t  \t\t<h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Profile picture updated</h6>\r\n");
      out.write("\t  \t\t<p class=\"text-gray mb-0\"> 18 Minutes ago </p>\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t  \t</a>\r\n");
      out.write("\t  \t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t  \t<h6 class=\"p-3 mb-0 text-center\">4 new messages</h6>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </li>\r\n");
      out.write("      <li class=\"nav-item nav-logout d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("          <i class=\"mdi mdi-power\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item nav-settings d-none d-lg-block\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("          <i class=\"mdi mdi-format-line-spacing\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("      <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("      <!-- partial -->\r\n");
      out.write("      <div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("  <ul class=\"nav\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"index.jsp\">\r\n");
      out.write("        <span class=\"menu-title kor\">메 인</span>\r\n");
      out.write("        <i class=\"mdi mdi-home menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#product\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">상품관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-basket menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"product\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/warehousing\">입고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/beReleased\">출고</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/product/stk\">재고</a></li> ");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#order\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">거래관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-barcode-scan menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"order\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/ordr\">발주</a></li>\r\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link kor\" href=\"");
      out.print( request.getContextPath() );
      out.write("/order/transfer\">이송</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#sales\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">매출관리</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-chart-line menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"sales\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item kor\"> <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/sales\">매출현황</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#approval\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("        <span class=\"menu-title kor\">전자결재</span>\r\n");
      out.write("        <i class=\"menu-arrow\"></i>\r\n");
      out.write("        <i class=\"mdi mdi-script menu-icon\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"collapse\" id=\"approval\">\r\n");
      out.write("        <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("          <li class=\"nav-item kor\"> <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/approval\">결재관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("        <!-- partial -->\r\n");
      out.write("        <div class=\"main-panel\">\r\n");
      out.write("          <div class=\"content-wrapper\">\r\n");
      out.write("              <i class=\"mdi mdi-close\" id=\"bannerClose\" style=\"display: none;\"></i>\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("              <h3 class=\"page-title kor\">\r\n");
      out.write("                <span class=\"page-title-icon bg-gradient-primary text-white mr-2\">\r\n");
      out.write("                  <i class=\"mdi mdi-script\"></i>\r\n");
      out.write("                </span> 결재관리 </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \t<div class=\"order-main\">\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-left: 0; margin-top: 48px; padding-left: 20px\">\r\n");
      out.write("\t\t\t\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-info btn-fw\" style=\"margin-right: 27px;\" data-target=\"waiting-approval\"> 결재대기함 </button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-info btn-fw\" style=\"margin-right: 27px;\" data-target=\"progress-approval\"> 진행결재함 </button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-info btn-fw\" data-target=\"complete-approval\"> 완료결재함 </button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br clear=\"both\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 grid-margin stretch-card\" style=\"margin-top: 26px\">\r\n");
      out.write("\t\t\t\t  <div class=\"card\">\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t<!-- 결제대기함 테이블 -->\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\"  id=\"waiting-approval\">\r\n");
      out.write("\t\t\t\t\t  <h4 class=\"card-title\">");
      out.print( today );
      out.write("</h4> \r\n");
      out.write("\t\t\t\t\t  <!-- <p class=\"card-description\"> 주문매장 : <span>All</span></p>\r\n");
      out.write("\t\t\t\t\t  <p class=\"card-description\"> 발주센터 : <span>All</span></p>\r\n");
      out.write("\t\t\t\t\t  <p class=\"card-description\"> 기간 : <span>All</span></p>  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  <table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 결재구분 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 상태 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 문서분류</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 문서번호 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 기안부서 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 제목 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 기안자 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 기안일시 </th>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 출고신청 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ? </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 12345 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 입고팀 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> XX 출고요청 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 홍길동 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 2020-07-06 </td>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  <!-- 진행결재함 테이블 -->\r\n");
      out.write("  \t\t\t\t\t<div class=\"card-body\"  id=\"progress-approval\" style=\"padding-top: 2rem;\">\r\n");
      out.write("\t\t\t\t\t  <h4 class=\"card-title\">");
      out.print( today );
      out.write("</h4> \r\n");
      out.write("\t\t\t\t\t  <table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 상태 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 문서분류</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 문서번호 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 제목 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 기안일시 </th>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td> !!!!!!!!!진행결재함 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ? </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 12345 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> XX 출고요청 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 2020-07-06 </td>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  <!-- 결재완료 테이블 -->\r\n");
      out.write("  \t\t\t\t\t<div class=\"card-body\"  id=\"complete-approval\" style=\"padding-top: 2rem;\">\r\n");
      out.write("\t\t\t\t\t  <h4 class=\"card-title\"><span>2020-07-07 (오늘날짜)</span></h4> \r\n");
      out.write("\t\t\t\t\t  <table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 상태 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 문서분류</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 문서번호 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 제목 </th>\r\n");
      out.write("\t\t\t\t\t\t\t<th> 기안일시 </th>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td> !!!!!!!!!결재완료함 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ? </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 12345 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> XX 출고요청 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> 2020-07-06 </td>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- content-wrapper ends -->\r\n");
      out.write("    \t   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- partial:partials/_footer.html -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("    <span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright © 2017 <a href=\"https://www.bootstrapdash.com/\" target=\"_blank\">BootstrapDash</a>. All rights reserved.</span>\r\n");
      out.write("    <span class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">Hand-crafted & made with <i class=\"mdi mdi-heart text-danger\"></i></span>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("          <!-- partial -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- main-panel ends -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- page-body-wrapper ends -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- container-scroller -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- plugins:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<!-- End plugin js for this page -->\r\n");
      out.write("<!-- inject:js -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/misc.js\"></script>\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Custom js for this page -->\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(  request.getContextPath() );
      out.write("/resources/bootstrap/js/todolist.js\"></script>\r\n");
      out.write("<!-- End custom js for this page -->");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("    $('[id$=\"-approval\"]').hide();\r\n");
      out.write("\t$('#waiting-approval').show();\t\r\n");
      out.write("});\r\n");
      out.write("$('.btn').click(function() {\r\n");
      out.write("    $('[id$=\"-approval\"]').hide();\r\n");
      out.write("    var target = '#' + $(this).data('target');\r\n");
      out.write("    $(target).show();\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
